apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-app-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: demo-app-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "services", "secrets", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demo-app-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: demo-app-sa
  namespace: default
roleRef:
  kind: Role
  name: demo-app-role
  apiGroup: rbac.authorization.k8s.io
