apiVersion: v1
kind: Service
metadata:
  name: multi-cloud-service
spec:
  type: NodePort  # For external access (change to LoadBalancer in cloud env)
  selector:
    app: multi-cloud-app
  ports:
    - protocol: TCP
      port: 8080          # Port exposed inside the cluster
      targetPort: 8080    # Port inside the container
      nodePort: 30081     # Port exposed externally (optional but fixed here)
